### ISSUE TITLE
Update https://docs.microsoft.com/en-us/azure to include Go

### ISSUE THREAD

**Issue by vladbarosan** [MicrosoftDocs/azure-docs-sdk-go#11]
Hi @sptramer, @joshgav  can we update https://docs.microsoft.com/en-us/azure/#pivot=get-started and
https://docs.microsoft.com/en-us/azure/#pivot=sdkstools to include `go` ? 

We point to there in the SDK repo and the samples repo but there is no link to GO from there. 

Also how to we get the changes in this repo to reflect in what actually gets displayed at https://docs.microsoft.com/en-us/go/azure/ ? Do we need to merge into the `live` branch ? if so, afterwards they are automatically picked up ?

**Comment by sptramer** [comment]
@vladbarosan @joshgav - We are working on this. The Go key art requires attribution under the [Attribution by CC 3.0 License](https://creativecommons.org/licenses/by/3.0/). There is not currently a way to display this information on docs and we are working on it.

**Comment by vladbarosan** [comment]
@sptramer I would say better to have it there even without a logo until we figure it out :) , @joshgav  ?

**Comment by sptramer** [comment]
Image-less PR up: https://github.com/MicrosoftDocs/azure-docs-pr/pull/33661

**Comment by vladbarosan** [comment]
@sptramer  I dont think we have access there ( at least I dont ).

@marstr do you have any idea how we can get some Go Key Art that does not require attribution ? ( to include Go here https://docs.microsoft.com/en-us/azure/#pivot=get-started along other languages)

**Comment by vladbarosan** [comment]
@sptramer also can we deploy the Go docs with the updated links ?

**Comment by marstr** [comment]
> @vladbarosan says:
@marstr do you have any idea how we can get some Go Key Art that does not require attribution

Looks like @sptramer has correctly assessed the situation: [The Go blog post about the Gophers](https://blog.golang.org/gopher) specifically mentions that all of the images are licensed under CC3. Until the docs page finds a way to get attribution right, we'll have to live without a Gopher image.

**Comment by vladbarosan** [comment]
@sptramer that being said can we update the go docs  and the links to it without the art work until we figure it out please ?

**Comment by sptramer** [comment]
@vladbarosan That requires approval from separate managers and people in charge of the Azure landing pages, not me. Follow the linked PR to stay up to date.

**Comment by vladbarosan** [comment]
ok, thanks, how can I get access to that repo ? apparently is private

**Comment by sptramer** [comment]
We now have a link to Go from the landing page. How to provide attribution is in process so that we can include images.
