### ISSUE TITLE
Typo in the azure go sdk profile version

### ISSUE THREAD

**Issue by bingosummer** [MicrosoftDocs/azure-docs-sdk-go#20]
https://github.com/MicrosoftDocs/azure-docs-sdk-go/blob/live/azure-go-sdk-conceptual/azure-sdk-go-install.md

`Right now, the only locked profile is version 2017-03-30` should be changed to `Right now, the only locked profile is version 2017-03-09`

**Comment by sptramer** [comment]
Thank you for the report, this has been fixed.
